In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [3]:
a=[1,4,3,5,6,5]
a

[1, 4, 3, 5, 6, 5]

In [9]:
y=np.array([1,2,5,7,8],float)
y

array([1., 2., 5., 7., 8.])

In [10]:
y.dtype

dtype('float64')

In [12]:
y.ndim

1

In [13]:
y[2:5]

array([5., 7., 8.])

In [18]:
q=np.array([[1,2,3,4,5],[3,4,5,6,7]])
q
q.ndim

2

In [20]:
q[0][3]

4

In [21]:
q.shape

(2, 5)

In [23]:
np.zeros((5,8),int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.ones((3,6),int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [25]:
np.full((4,3),22)

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

In [26]:
np.arange(2,16,3)

array([ 2,  5,  8, 11, 14])

In [27]:
np.linspace(2,8,20)

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

In [29]:
np.random.randint(1,10,6)

array([9, 3, 2, 4, 2, 5])

In [30]:
np.random.randint(1,10,(2,4))

array([[3, 6, 4, 3],
       [7, 3, 9, 7]])

In [32]:
arr=np.array([1,3,4,5])
arr=np.append(arr,6)

In [33]:
np.insert(arr,0,10)

array([10,  1,  3,  4,  5,  6])

In [37]:
np.delete(arr,3)

array([1, 3, 4, 6])

In [18]:
w=np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13],[13,14,15,16,17]])
w.ndim
w

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17]])

In [13]:
np.insert(w,2,55,axis=1)

array([[ 1,  2, 55,  3,  4],
       [ 5,  6, 55,  7,  8],
       [ 9, 10, 55, 11, 12]])

In [14]:
np.delete(w,1,axis=1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [19]:
w

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17]])

In [20]:
w.shape

(4, 5)

In [21]:
w[1:]

array([[ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17]])

In [23]:
w[1:3]

array([[ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13]])

In [27]:
w

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17]])

In [34]:
w[1:3,2:4]

array([[ 7,  8],
       [11, 12]])